version: '3.1'
services:
  web:
    image: kevenli/freedb:develop
    # volumes:
    #   - ./db.sqlite3:/app/db.sqlite3:Z
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "mongo:/data/db"

volumes:
  mongo: {}