version: '3.1'
services:
  web:
    image: kevenli/freedb:develop
    volumes:
      - ./db.sqlite3:/app/db.sqlite3:Z
    ports:
      - 8000:81
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
    environment:
      MONGODB_URL: mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "mongo:/data/db"

volumes:
  mongo: {}
