version: '3.1'
services:
  web:
    image: freedb
    volumes:
      - ./data:/app/data:z
    ports:
      - 8000:8000
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
    environment:
      MONGODB_URL: mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "mongo:/data/db"

volumes:
  mongo: {}
