# Generated by Django 2.1.7 on 2020-07-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='actual_col_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
